plugins = []
headers = []

[functions]

[functions."*"]

[build]
publish = "/Users/emmanuelrwozi/rwandair-cargo-portal/.claude/worktrees/compassionate-varahamihira/build"
publishOrigin = "ui"
commandOrigin = "ui"
base = "/Users/emmanuelrwozi/rwandair-cargo-portal/.claude/worktrees/compassionate-varahamihira"
command = "npm run build"

[build.environment]

[build.processing]

[build.processing.css]

[build.processing.html]

[build.processing.images]

[build.processing.js]

[build.services]

[[redirects]]
from = "/"
to = "/login.html"
status = 200.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]

[[redirects]]
from = "/portal"
to = "/portal.html"
status = 200.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]

[[redirects]]
from = "/gsa"
to = "/portal-gsa.html"
status = 200.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]

[[redirects]]
from = "/warehouse"
to = "/portal-warehouse.html"
status = 200.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]

[[redirects]]
from = "/management"
to = "/portal-management.html"
status = 200.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]

[[redirects]]
from = "/planning"
to = "/portal-planning.html"
status = 200.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]

[[redirects]]
from = "/*"
to = "/login.html"
status = 200.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]