export const dynamic = "force-dynamic"
import { NextResponse } from 'next/server'
import { getAdminClient } from '@/lib/supabase-admin'
import { createServerSupabaseClient } from '@/lib/supabase-server'

export async function POST(request: Request) {
  try {
    const supabase = await createServerSupabaseClient()
    const supabaseAdmin = getAdminClient()
    const { data: { user } } = await supabase.auth.getUser()
    if (!user) return NextResponse.json({ error: 'Unauthorized' }, { status: 401 })

    // Get exporter profile
    const { data: exporter } = await supabaseAdmin
      .from('exporters')
      .select('id, status')
      .eq('user_id', user.id)
      .single()

    if (!exporter || exporter.status !== 'approved') {
      return NextResponse.json({ error: 'Exporter account not approved' }, { status: 403 })
    }

    const body = await request.json()
    const {
      product_type,
      quantity,
      weight_kg,
      destination_country,
      destination_airport,
      preferred_departure_date,
      buyer_name,
      invoice_value_usd,
      incoterm,
      // Water freight fields
      transport_mode,
      water_type,
      vessel_name,
      voyage_number,
      port_of_loading,
      port_of_discharge,
      lake_name,
      vessel_operator,
      port_cutoff_date,
      bill_of_lading_number,
      container_number,
      container_type,
    } = body

    const isWater = transport_mode === 'water'

    // Create shipment (shipment_id auto-generated by trigger)
    const { data: shipment, error } = await supabaseAdmin
      .from('shipments')
      .insert({
        shipment_id: '', // trigger will override
        exporter_id: exporter.id,
        product_type,
        quantity: parseInt(quantity),
        weight_kg: parseFloat(weight_kg),
        destination_country,
        destination_airport: destination_airport || '',
        preferred_departure_date,
        buyer_name,
        invoice_value_usd: parseFloat(invoice_value_usd),
        incoterm,
        status: 'Draft',
        transport_mode: transport_mode || 'air',
        ...(isWater && {
          water_type: water_type || null,
          vessel_name: vessel_name || null,
          voyage_number: voyage_number || null,
          port_of_loading: port_of_loading || null,
          port_of_discharge: port_of_discharge || null,
          lake_name: lake_name || null,
          vessel_operator: vessel_operator || null,
          port_cutoff_date: port_cutoff_date || null,
          bill_of_lading_number: bill_of_lading_number || null,
          container_number: container_number || null,
          container_type: container_type || null,
        }),
      })
      .select()
      .single()

    if (error) return NextResponse.json({ error: error.message }, { status: 400 })

    // Log initial status
    await supabaseAdmin.from('status_logs').insert({
      shipment_id: shipment.id,
      previous_status: null,
      new_status: 'Draft',
      changed_by: user.id,
      note: 'Shipment created',
    })

    return NextResponse.json({ success: true, shipment })
  } catch (err) {
    console.error('Shipment creation error:', err)
    return NextResponse.json({ error: 'Internal server error' }, { status: 500 })
  }
}
